name: switchbot_api_dio
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  crypto: ^3.0.3
  dio: ^5.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  http_mock_adapter: ^0.4.4
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  pedantic_mono: ^1.23.0
  test: ^1.21.0

flutter:
  assets:
    - assets/test/json/
