name: test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: read-flutter-version
        name: Read fvm_config.json
        run: echo version=$(cat .fvm/fvm_config.json | jq -r '.flutterSdkVersion') >> $GITHUB_OUTPUT
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.read-flutter-version.version }}
          channel: 'stable'
      - name: Test Preparation
        run: |
          flutter pub get
          flutter pub run build_runner build --build-filter='test/**/*.dart'
      - name: Run Test
        run: flutter test
